### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by home1800** [drkno/PlexSSOv2#29]
Getting an error when trying to set accessControls. I've got grafana under status.domain.com
Setting accessControls in any way will result in this error:
```{"EventId":1,"LogLevel":"Error","Category":"Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware","Message":"An unhandled exception has occurred while executing the request.","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.
    at PlexSSO.Service.Auth.AuthenticationValidator.\u003C\u003Ec__DisplayClass3_0.\u003CGetFirstMatchingAccessControl\u003Eb__0(AccessControl control) in /backend/PlexSSO/Service/Auth/AuthenticationValidator.cs:line 78
    at System.Linq.Enumerable.WhereArrayIterator\u00601.MoveNext()
    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable\u00601 source, Func\u00602 predicate, Boolean\u0026 found)
    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable\u00601 source, Func\u00602 predicate)
    at PlexSSO.Service.Auth.AuthenticationValidator.GetFirstMatchingAccessControl(ServiceName serviceName, ServiceUri serviceUri, Identity identity) in /backend/PlexSSO/Service/Auth/AuthenticationValidator.cs:line 77
    at PlexSSO.Service.Auth.AuthenticationValidator.ValidateAuthenticationStatus(Identity identity, ServiceName serviceName, ServiceUri serviceUri) in /backend/PlexSSO/Service/Auth/AuthenticationValidator.cs:line 27
    at PlexSSO.Controllers.SsoController.Get() in /backend/PlexSSO/Controllers/SsoController.cs:line 22
    at lambda_method1(Closure , Object , Object[] )
    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync() --- End of stack trace from previous location ---
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location ---
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeNextResourceFilter\u003Eg__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() --- End of stack trace from previous location ---
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","State":{"Message":"An unhandled exception has occurred while executing the request.","{OriginalFormat}":"An unhandled exception has occurred while executing the request."}}
```

since servicename and uri where listed in the error I've doublechecked that they are in my nginx.conf, which they are, just like in the example configs. plexsso is under login.domain.com and the rest is pretty much 1:1 example. I've checked nginx logs too without any indication of it blocking anything.

```
{
  "configFile": "/config/",
  "pluginDirectory": "/app",
  "plexPreferencesFile": null,
  "serverIdentifier": "xxxxxxxx",
  "cookieDomain": ".domain.com",
  "defaultAccessDeniedMessage": "Sorry, you were denied access to this page. Contact admin if you think this was an error.",
  "accessControls": {
    "status": [
      {
        "path": "/",
        "minimumAccessTier": "Owner",
        "controlType": "Block",
      }
    ]
  }
} 
```

can provide further configs if needed.

**Comment by drkno** [comment]
This should only occur if `X-PlexSSO-Original-URI` was not set for some reason.
However that in itself shouldn't cause an exception so I've added https://github.com/drkno/PlexSSOv2/commit/690dc5101ee56048bcddf6aca9dba089fbe58984 to prevent it occurring. The build is automated and should have the changes within a few mins of this message.
